AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance using Jenkins

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0150ccaf51ab55a51
      InstanceType: t2.micro
